global using OpenTK.Mathematics;
global using OpenTK.Windowing.GraphicsLibraryFramework;
global using System.Drawing;
global using OpenTK.Graphics.OpenGL4;
global using System.Runtime.Versioning;
global using System.Drawing.Imaging;
global using PixelFormat = OpenTK.Graphics.OpenGL4.PixelFormat;
global using OpenTK.Windowing.Desktop;
global using OpenTK.Windowing.Common;
global using System.Globalization;

global using EOCS.Base;
global using EOCS.Core;
global using EOCS.Objects;
global using EOCS.Render;
global using EOCS.TextRender.TextRender;
global using EOCS.Utils.Colors;
global using EOCS.ConfigManager;
global using EOCS.GameConsole;
global using EOCS.PrimitiveFigures._2D.Primitive2D_AbstractClass;
global using EOCS.PrimitiveFigures._2D;